### ISSUE TITLE
[Meta] MVP for Alerting in Discover

### ISSUE THREAD

**Issue by stacey-gammon** [stacey-gammon/kibana-dependency-tracking#56]
With the introduction of the alerting service, we want to introduce support for configuring alerts based on a specific view in Discover. Based on discussions with alerting, app, & arch teams, these are the steps we've identified to get us there:
- ~[ ] [Add support for ES DSL "search alert" in Alerting service](https://github.com/elastic/kibana/issues/61313)~
  - First-class support for ES DSL is not needed for MVP; we can simply use the `callCluster` service in the executor
- [ ] [Expose tools from data plugin to convert a query to raw DSL for use in alert](https://github.com/elastic/kibana/issues/71096)
- [ ] [Create alert executor to define an alert based on ES DSL](https://github.com/elastic/kibana/issues/71097)
- [ ] [Build alert creation UI for Discover](https://github.com/elastic/kibana/issues/71098)

## Concepts
![image](https://user-images.githubusercontent.com/32550316/79258269-c0265b00-7e3f-11ea-9efc-4979a4cdf148.png)

Clicking on create alert opens a flyout. The flyout takes into account the search bar query and filters. Whatever is in blue is configurable:  
![image](https://user-images.githubusercontent.com/32550316/79258399-e946eb80-7e3f-11ea-818f-d66b8faff03b.png)

## Architecture
![Alerting in Discover   Visualize - Discover](https://user-images.githubusercontent.com/1608770/86930834-afab1700-c0f4-11ea-84ba-8dee2464adfd.jpeg)

---

Related meta issue for alerting on Dashboards: https://github.com/elastic/kibana/issues/71560

cc @AlonaNadler @shaunmcgough @arisonl @rayafratkina @stacey-gammon @elastic/kibana-alerting-services @elastic/kibana-app @elastic/kibana-app-arch
