### ISSUE TITLE
[Meta] Kibana support for ES aggregations

### ISSUE THREAD

**Issue by stacey-gammon** [stacey-gammon/kibana-dependency-tracking#58]
This issue will track support for ES aggregations within Kibana. The list below is not in a priority order, just an inventory.

## [Bucket aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket.html)
| Type | AggConfigs⁴  | Visualize | Lens | TSVB | Known issues & notes|
|:-----|:---------------:|:----------:|:---------:|:---------:|:----------------:|
|[Adjacency matrix](https://github.com/elastic/kibana/issues/30161)|   |   |   |   |  |
|Histogram| ✔️ | ✔️ |   |   |   | Auto interval requires ES support https://github.com/elastic/elasticsearch/issues/31828
|Date histogram| ✔️ | ✔️ | ✔️ | ✔️ | https://github.com/elastic/kibana/issues/56319, https://github.com/elastic/kibana/issues/27410, https://github.com/elastic/kibana/issues/3787|
|Auto-interval date histogram| :small_blue_diamond: | :small_blue_diamond: | :small_blue_diamond: | :small_blue_diamond: | ¹ see Notes below |
|Children| | | | | 
|Composite| | | | |
|Date range| ✔️ | ✔️ | | |https://github.com/elastic/kibana/issues/9916|
|Diversified sampler| | | | | #67388 |
|Filter| ✔️ | ✔️| |✔️ | 
|Filters| ✔️ | ✔️| |✔️|https://github.com/elastic/kibana/issues/17674|
|Geo distance| | | | | 
|GeoHash grid| ✔️ | ✔️| | | | 
|GeoTile grid| ✔️ | | | | 
|Global| :small_blue_diamond: | :small_blue_diamond: | :small_blue_diamond: | :small_blue_diamond: | ² see Notes below | 
|IP range| ✔️ | ✔️ | | | | 
|Missing| | | | | #67391 | 
|[Nested](https://github.com/elastic/kibana/issues/1084)| | | | | 
|Reverse nested| | | | | | 
|Parent| | | | | | 
|Range| ✔️ | ✔️ | | | | 
|[Sampler](https://github.com/elastic/kibana/issues/25983)| | | | | | 
|Terms| ✔️ | ✔️|✔️|✔️|https://github.com/elastic/kibana/issues/42467, https://github.com/elastic/kibana/issues/17454|
|Significant terms| ✔️ | ✔️| ✔️| ✔️| https://github.com/elastic/kibana/issues/40368|
|[Rare terms](https://github.com/elastic/kibana/issues/26340)| | | | | #67393 |
|[Significant text](https://github.com/elastic/kibana/issues/31614)| | | | | #67394 | 

## [Metrics aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics.html)
| Type | AggConfigs⁴ | Visualize | Lens | TSVB | Known issues & notes|
|:-----|:---------------:|:----------:|:---------:|:---------:|:----------------:|
|Average/sum| ✔️ | ✔️| ✔️| ✔️| |
|Weighted average| | | | | #67399 | 
|Cardinality| ✔️ | ✔️| ✔️| ✔️| |
|Geo bounds| ✔️ | | | | | 
|Geo centroid| ✔️ | | | | | 
|Max/min| ✔️ | ✔️| ✔️| ✔️| |
|Percentiles| ✔️ | ✔️| https://github.com/elastic/kibana/issues/74574 | ✔️|https://github.com/elastic/kibana/issues/20084|
|Percentiles Rank| ✔️ | ✔️| | ✔️| |
|[Scripted metric](https://github.com/elastic/kibana/issues/2646)| | | | | |
|[Stats](https://github.com/elastic/kibana/issues/20084)| | | | | |
|[String stats](https://github.com/elastic/kibana/issues/51510)| | | | | https://github.com/elastic/kibana/issues/51510 |
|[Extended stats](https://github.com/elastic/kibana/issues/10533)| | | | | |
|[Top hits](https://github.com/elastic/kibana/issues/26850)| ✔️ | ✔️ | | ✔️³ | |
|[Value count](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-valuecount-aggregation.html)| | | https://github.com/elastic/kibana/issues/74910 | ✔️ | #67403 |
|[Median absolute deviation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-median-absolute-deviation-aggregation.html)| | | | | |
|[Boxplot](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-metrics-boxplot-aggregation.html)| | | | | https://github.com/elastic/kibana/issues/4157 |
|[Event rate and average rate](https://github.com/elastic/elasticsearch/pull/61369) | | | | | 

## [Matrix aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-matrix.html)
| Type | AggConfigs⁴ | Visualize | Lens | TSVB | Known issues & notes|
|:-----|:---------------:|:----------:|:---------:|:---------:|:----------------:|
|Matrix stats| | | | | |

## [Pipeline aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline.html)
| Type | AggConfigs⁴ | Visualize | Lens | TSVB | Known issues & notes|
|:-----|:---------------:|:----------:|:---------:|:---------:|:----------------:|
|Avg bucket| ✔️ | ✔️ | |✔️| |
|Derivative| ✔️ | ✔️ | |✔️| |
|Max/min bucket| ✔️ | ✔️| |✔️| |
|Sum bucket| ✔️ | ✔️ | |✔️| |
|Stats/extended stats bucket| | | | |
|[Percentile bucket](https://github.com/elastic/kibana/issues/20087)| | | | | |
|Moving average| ✔️ | ✔️ | | ✔️| |
|[Moving function](https://github.com/elastic/kibana/issues/65382)| | | |  | |
|[Moving percentiles](https://github.com/elastic/kibana/issues/65379)| | | |  | |
|[Normalize](https://github.com/elastic/elasticsearch/pull/56399)| | | |  | #67402 |
|Cumulative sum| ✔️ | ✔️| ✔️| ✔️| |
|[Cumulative cardinality](https://github.com/elastic/kibana/pull/57412)| | | | | #70337 |
|[Bucket script](https://github.com/elastic/kibana/issues/4707)| | | |✔️| #67405 |
|Bucket selector| | | | | |
|Bucket sort| | | | | |
|Serial differencing| ✔️ | ✔️ | | ✔️| |

## Other aggregation ideas (not directly supported by ES)
 - [ ] Filter ratio metric aggregation: https://github.com/elastic/kibana/issues/20515 https://github.com/elastic/kibana/issues/42385 
 - [ ] Cumulative distribution: https://github.com/elastic/kibana/issues/3905
 - [ ] Articulate approximate nature of aggregations in the UI: https://github.com/elastic/kibana/issues/2363
- [ ] Rate https://github.com/elastic/kibana/issues/46627
- [ ] Average event rate https://github.com/elastic/kibana/issues/62375
- [ ] Percentage change from previous https://github.com/elastic/kibana/issues/62381

## Notes

1) There are no plans to support Auto-interval date histogram in Kibana, since we're supporting `auto` interval via an implementation in Kibana. Due to technical reasons we'll keep using that Kibana side implementation for `auto` intervals. #4312 for the enhancement to support `auto` interval on all fields (not only the primary time field of an index pattern).
2) The _global_ aggregation is meant to make a part of an aggregation ignore the search query. This is useful if you want to return documents and an aggregation in the same request. Since Kibana doesn't have that use-case, and can freely define the query (or a filters aggregation at any level it wants), there is currently no generic use-case to support _Global_ in Kibana.
3) TSVB only supports top hits on numeric fields, no string fields.
4) `AggConfigs` lives in the `data` plugin's `search` service, and is used behind the scenes for aggregations in Visualize and Lens. Work on `AggConfigs` is tracked in #60126. A checkmark here means that we have the technical foundation to implement it into visualizations, but not that it's already available to the user anywhere.
