### ISSUE TITLE
Lazy-load visualizations

### ISSUE THREAD

**Issue by stacey-gammon** [stacey-gammon/kibana-dependency-tracking#61]
With the new platform, soon all visualizations will be loaded for each page/app a user loads because registerings are ran in the setup phase and pull in the definition of a visulization which also contains the render logic. Currently there is no lazy dynamic import step in there to load the heavy part of visualizations only when actually required to render. Especially for visualization types like vega or timelion which rely on complete rendering libraries under the hood not used anywhere else, this can bloat the amount of Javascript evaluated when Kibana is loaded and slow down the startup.

Tasks:
* Validate the impact of loading all visualizations with their complete implementation up front whether the effort is even worth it. If it is...
* Check whether the visualizations registry can be improved somehow to make this task easier
* Discuss with app arch team and implement if appropriate
* [ ] Lazy-load vega
* [ ] Lazy-load timelion
* [ ] Lazy-load vislib
* [ ] Lazy-load tagcloud
* [ ] Lazy-load TSVB
* [ ] Lazy-load markdown
* [ ] Lazy-loading in Lens
