### ISSUE TITLE
[Meta] Discarded search request cancellation

### ISSUE THREAD

**Issue by stacey-gammon** [stacey-gammon/kibana-dependency-tracking#83]
This is a list of the remaining places we still need to implement cancellation of discarded queries:

- [ ] TSVB (https://github.com/elastic/kibana/issues/46353)
- [x] Coordinate map fit data bounds (https://github.com/elastic/kibana/issues/46359)
- [ ] Vega (https://github.com/elastic/kibana/issues/46352)
- [ ] Timelion (https://github.com/elastic/kibana/issues/46354)
- [x] KQL/filter editor suggestions (https://github.com/elastic/kibana/issues/48797)
